services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API de MinIO
      - "9001:9001"   # Consola web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - cloudnet

  cloudbox:
    build: .
    container_name: cloudbox_app
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    stdin_open: true
    tty: true
    networks:
      - cloudnet
    volumes:
      - ./archivos:/app/archivos

networks:
  cloudnet:
    driver: bridge
